// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthDept struct {
	Id       int64  `json:"id"`
	DeptName string `json:"deptName"`
	DeptCode string `json:"deptCode"`
}

type AuthMenu struct {
	Id             int64       `json:"id"`
	ParentId       int64       `json:"parentId"`
	MenuName       string      `json:"menuName"`
	MenuType       string      `json:"menuType"`
	Path           string      `json:"path"`
	Component      *string     `json:"component"`
	ExternalUrl    *string     `json:"externalUrl"`
	Icon           *string     `json:"icon"`
	PermissionCode *string     `json:"permissionCode"`
	SortOrder      int64       `json:"sortOrder"`
	Visible        int64       `json:"visible"`
	Children       []*AuthMenu `json:"children"`
}

type AuthRole struct {
	Id       int64  `json:"id"`
	RoleName string `json:"roleName"`
	RoleCode string `json:"roleCode"`
}

type AuthUser struct {
	Id            int64      `json:"id"`
	Username      string     `json:"username"`
	Nickname      string     `json:"nickname"`
	Avatar        *string    `json:"avatar"`
	Phone         *string    `json:"phone"`
	Email         *string    `json:"email"`
	Dept          *AuthDept  `json:"dept,optional"`
	Roles         []AuthRole `json:"roles"`
	LastLoginTime *string    `json:"lastLoginTime"`
	LastLoginIp   *string    `json:"lastLoginIp"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginToken struct {
	TokenName  string `json:"tokenName"`
	TokenValue string `json:"tokenValue"`
	ExpiresIn  int64  `json:"expiresIn"`
}
