swagger:
  enabled: true

database:
  url: postgres://192.168.1.48:5432/base_project_golang?sslmode=disable
  username: pgsql
  password: pgsql

jwt:
  secret: replace-with-a-random-local-development-jwt-secret

log:
  level: debug
  format: text
