CREATE TABLE sys_dept (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL DEFAULT 0,
    dept_name VARCHAR(100) NOT NULL,
    dept_code VARCHAR(50) NOT NULL,
    leader VARCHAR(50), phone VARCHAR(20), email VARCHAR(100),
    sort_order INTEGER NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 1,
    is_builtin SMALLINT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT, update_by BIGINT,
    deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_dept_code UNIQUE (dept_code)
);
CREATE INDEX idx_dept_parent_id ON sys_dept (parent_id);
CREATE INDEX idx_dept_deleted_status_sort ON sys_dept (deleted, status, sort_order);

CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    phone VARCHAR(20), email VARCHAR(100), avatar VARCHAR(255),
    gender VARCHAR(20) NOT NULL DEFAULT 'UNSPECIFIED',
    dept_id BIGINT,
    status SMALLINT NOT NULL DEFAULT 1,
    is_builtin SMALLINT NOT NULL DEFAULT 0,
    last_login_time TIMESTAMP, last_login_ip VARCHAR(45), remark VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT, update_by BIGINT,
    deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_username UNIQUE (username)
);
CREATE INDEX idx_user_dept_id ON sys_user (dept_id);
CREATE INDEX idx_user_deleted_status ON sys_user (deleted, status);

CREATE TABLE sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL, role_code VARCHAR(50) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0,
    is_builtin SMALLINT NOT NULL DEFAULT 0, remark VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT, update_by BIGINT, deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_role_code UNIQUE (role_code)
);
CREATE INDEX idx_role_deleted_status_sort ON sys_role (deleted, status, sort_order);

CREATE TABLE sys_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL DEFAULT 0, menu_name VARCHAR(50) NOT NULL,
    menu_type VARCHAR(20) NOT NULL, path VARCHAR(255), component VARCHAR(255),
    external_url VARCHAR(500), icon VARCHAR(100), permission_code VARCHAR(100),
    sort_order INTEGER NOT NULL DEFAULT 0, visible SMALLINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1, is_builtin SMALLINT NOT NULL DEFAULT 0,
    remark VARCHAR(500), create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT, update_by BIGINT, deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_permission_code UNIQUE (permission_code)
);
CREATE INDEX idx_menu_parent_id ON sys_menu (parent_id);
CREATE INDEX idx_menu_deleted_status_sort ON sys_menu (deleted, status, sort_order);
CREATE INDEX idx_menu_type ON sys_menu (menu_type);

CREATE TABLE sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, role_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, create_by BIGINT,
    CONSTRAINT uk_user_role UNIQUE (user_id, role_id)
);
CREATE INDEX idx_user_role_user_id ON sys_user_role (user_id);
CREATE INDEX idx_user_role_role_id ON sys_user_role (role_id);

CREATE TABLE sys_role_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL, menu_id BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, create_by BIGINT,
    CONSTRAINT uk_role_menu UNIQUE (role_id, menu_id)
);
CREATE INDEX idx_role_menu_role_id ON sys_role_menu (role_id);
CREATE INDEX idx_role_menu_menu_id ON sys_role_menu (menu_id);

CREATE TABLE sys_dict_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_name VARCHAR(100) NOT NULL, dict_code VARCHAR(100) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0,
    is_builtin SMALLINT NOT NULL DEFAULT 0, remark VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT, update_by BIGINT, deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_dict_code UNIQUE (dict_code)
);
CREATE INDEX idx_dict_type_deleted_status_sort ON sys_dict_type (deleted, status, sort_order);

CREATE TABLE sys_dict_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type_id BIGINT NOT NULL, dict_label VARCHAR(100) NOT NULL, dict_value VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0, remark VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT, update_by BIGINT, deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_dict_type_value UNIQUE (dict_type_id, dict_value)
);
CREATE INDEX idx_dict_data_type_id ON sys_dict_data (dict_type_id);
CREATE INDEX idx_dict_data_deleted_sort ON sys_dict_data (deleted, sort_order);

CREATE TABLE sys_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL, login_status VARCHAR(20) NOT NULL,
    login_ip VARCHAR(45), login_location VARCHAR(100), browser VARCHAR(100), os VARCHAR(100),
    user_agent VARCHAR(500), message VARCHAR(500),
    login_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_login_log_username ON sys_login_log (username);
CREATE INDEX idx_login_log_status ON sys_login_log (login_status);
CREATE INDEX idx_login_log_time ON sys_login_log (login_time);

CREATE TABLE sys_oper_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name VARCHAR(100) NOT NULL, operation_type VARCHAR(50) NOT NULL,
    request_method VARCHAR(20), request_url VARCHAR(500), operator_id BIGINT,
    operator_name VARCHAR(50), operator_ip VARCHAR(45), operator_location VARCHAR(100),
    request_params TEXT, response_result TEXT, cost_time BIGINT,
    operation_status VARCHAR(20) NOT NULL, error_message TEXT,
    operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_oper_log_module_name ON sys_oper_log (module_name);
CREATE INDEX idx_oper_log_operation_type ON sys_oper_log (operation_type);
CREATE INDEX idx_oper_log_operator_id ON sys_oper_log (operator_id);
CREATE INDEX idx_oper_log_operation_status ON sys_oper_log (operation_status);
CREATE INDEX idx_oper_log_operation_time ON sys_oper_log (operation_time);

CREATE TABLE sys_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL, storage_name VARCHAR(255) NOT NULL,
    extension VARCHAR(50), mime_type VARCHAR(100), file_size BIGINT NOT NULL DEFAULT 0,
    file_md5 VARCHAR(32), storage_path VARCHAR(500) NOT NULL, access_url VARCHAR(500),
    business_module VARCHAR(50), status SMALLINT NOT NULL DEFAULT 1, remark VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT, update_by BIGINT, deleted SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_file_md5 ON sys_file (file_md5);
CREATE INDEX idx_file_business_module ON sys_file (business_module);
CREATE INDEX idx_file_deleted_status ON sys_file (deleted, status);
CREATE INDEX idx_file_create_time ON sys_file (create_time);

CREATE TABLE sys_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR(100) NOT NULL, config_key VARCHAR(100) NOT NULL,
    config_value VARCHAR(500), config_type VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    value_type VARCHAR(20) NOT NULL DEFAULT 'TEXT', status SMALLINT NOT NULL DEFAULT 1,
    is_builtin SMALLINT NOT NULL DEFAULT 0, remark VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT, update_by BIGINT, deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_config_key UNIQUE (config_key)
);
CREATE INDEX idx_config_type ON sys_config (config_type);
CREATE INDEX idx_config_deleted_status ON sys_config (deleted, status);
