// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/EziosWJ/base-project-golang/base-go-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me",
				Handler: CurrentUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menus",
				Handler: CurrentUserMenusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)
}
